FROM python:3.10.12

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

# Environment
ARG ENV

# API config
ARG API_NAME
ARG URL_SCHEME
ARG SERVER_NAME
ARG PORT

# Security
ARG SECRET_KEY
ARG ALGORITHM

# MySQL configuration
ARG MYSQL_HOST
ARG MYSQL_PORT
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DB

# Mercado pago
ARG MP_ACCESS_TOKEN

# Environment
ENV ENV=$ENV

# API config
ENV API_NAME=$API_NAME
ENV URL_SCHEME=$URL_SCHEME
ENV SERVER_NAME=$SERVER_NAME
ENV PORT=$PORT

# Security
ENV SECRET_KEY=$SECRET_KEY
ENV ALGORITHM=$ALGORITHM

# MySQL configuration
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_PORT=$MYSQL_PORT
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_DB=$MYSQL_DB

# Mercado pago
ENV MP_ACCESS_TOKEN=$MP_ACCESS_TOKEN

ENV FLASK_APP=main.py

EXPOSE 5000

CMD ["flask", "run", "--host", "0.0.0.0"]