networks:
  mynetwork:
    name: "mynetwork"
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: myslq
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '3306:3306'
    networks:
      - mynetwork
  
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - '5000:5000'
    environment:
      - ENV=${ENV}
      - API_NAME=${API_NAME}
      - URL_SCHEME=${URL_SCHEME}
      - SERVER_NAME=${SERVER_NAME}
      - PORT=5000
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=ecommerce_db
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}
    depends_on:
      - mysql
    networks:
      - mynetwork