from flask import Blueprint, request

# Controller
from src.controllers.PaymentController import PaymentController

# Security
from src.utils.Security import Security

payment = Blueprint('payment', __name__)


@payment.route('/generate/<string:address_id>', methods=['GET'])
@Security.verify_session
def generate_payment_link(user_id, address_id):
    """
    Generates a payment link for the given user and address.

    Parameters:
    - user_id (str): The ID of the user.
    - address_id (str): The ID of the address.

    Returns:
    - response (dict): The generated payment link.
    """
    if request.method == 'GET':
        response = PaymentController.generate_preference(user_id, address_id)
        return response

@payment.route('/success', methods=['GET'])
def payment_success():
    return "success"


@payment.route('/pending', methods=['GET'])
def payment_pending():
    return "pending"


@payment.route('/failure', methods=['GET'])
def payment_failure():
    return "failure"


@payment.route('/notification/<string:user_id>/<string:address_id>', methods=['POST'])
def notification(user_id, address_id):
    """
    Handle the notification endpoint for payment.

    Args:
        user_id (str): The ID of the user.
        address_id (str): The ID of the address.

    Returns:
        str: The response generated by the PaymentController.
    """
    if request.method == 'POST':
        topic = request.args.get('topic')
        payment_id = request.args.get('id')
        response = PaymentController.generate_order(
            user_id, address_id, topic, payment_id)
        return response
